# Generated by Django 5.2.9 on 2026-01-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('workshops', 'Workshops'), ('ctf', 'CTF'), ('seminars', 'Seminars'), ('hackathons', 'Hackathons'), ('other', 'Other')], default='other', max_length=50)),
                ('image_url', models.URLField(max_length=500)),
                ('public_id', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
