# Generated by Django 5.2.9 on 2026-01-18 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_event_date_event_created_at_event_event_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_team_event',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='team_size_max',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='event',
            name='team_size_min',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='registration',
            name='team_members',
            field=models.TextField(blank=True, help_text='Comma separated names or JSON'),
        ),
        migrations.AddField(
            model_name='registration',
            name='team_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
