# Generated by Django 5.2.9 on 2026-01-25 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_payment_amount_event_requires_payment_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='content_blocks',
            field=models.JSONField(blank=True, default=list, help_text='List of {title, content, list[], items[]} for premium rendering'),
        ),
        migrations.AddField(
            model_name='event',
            name='coordinators',
            field=models.JSONField(blank=True, default=list, help_text='List of {name, phone, role}'),
        ),
        migrations.AddField(
            model_name='event',
            name='prize',
            field=models.CharField(blank=True, help_text='Prize pool amount or description', max_length=255),
        ),
    ]
