# Generated by Django 5.2.9 on 2026-01-25 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_content_blocks_event_coordinators_event_prize'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='duration',
            field=models.CharField(blank=True, help_text='e.g. 2 Hours', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.CharField(blank=True, help_text='e.g. 11:00 AM', max_length=100),
        ),
    ]
