# Generated by Django 5.2.9 on 2026-02-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_registration_phone_number_alter_registration_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='college',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='registration',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='registration',
            name='year_of_study',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
