# Generated by Django 5.1.5 on 2026-09-26 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_registration_college_registration_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='duration',
        ),
    ]
