# Generated by Django 5.1.5 on 2026-09-26 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_remove_event_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='time',
        ),
    ]
